{% set name = "xtl" %}
{% set version = "0.2.1" %}
{% set sha256 = "47afc54523c43ee8d808570c8b5da75eacf82dfbb31587f798de5cbc9f2262d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/xtl/xbasic_fixed_string.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtl/xtlConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtl/xtlConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtl\xbasic_fixed_string.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtlConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtlConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The QuantStack tools library'
  description: 'Basic tools (containers, algorithms) used by other packages from Quantstack'
  doc_url: http://xtl.readthedocs.io
  dev_url: https://github.com/QuantStack/xtl

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
