{% set name = "xtl" %}
{% set version = "0.6.21" %}
{% set sha256 = "97137014fa5da2a3598a267d06c8e28490b2e1c75b8f52358738bedb526fc771" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host: []  # Empty host dependency section

test:
  commands:
    - test -f ${PREFIX}/include/xtl/xbasic_fixed_string.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtl/xtlConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtl/xtlConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtl\xbasic_fixed_string.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtl\xtlConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtl\xtlConfigVersion.cmake (exit 1)  # [win]

about:
  home: http://quantstack.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The QuantStack tools library
  description: Basic tools (containers, algorithms) used by other packages from Quantstack
  doc_url: http://xtl.readthedocs.io
  dev_url: https://github.com/QuantStack/xtl

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
    - conda-forge/xtensor
