{% set name = "xtl" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtl/archive/{{ version }}.tar.gz
  sha256: 44fb99fbf5e56af5c43619fc8c29aa58e5fad18f3ba6e7d9c55c111b62df1fbb

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  run:
    - nlohmann_json

test:
  source_files:
    - test
  requires:
    - doctest
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  commands:
    - test -f ${PREFIX}/include/xtl/xbasic_fixed_string.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtl/xtlConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtl/xtlConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtl\xbasic_fixed_string.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtl\xtlConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtl\xtlConfigVersion.cmake (exit 1)  # [win]
    - cmake -S test -B test -G Ninja
    - ninja -C test test_xtl
    - ./test/test_xtl  # [not win]
    - .\test\test_xtl  # [win]
about:
  home: https://github.com/xtensor-stack/xtl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xtensor-stack tools library
  description: Basic tools (containers, algorithms) used by other packages from the xtensor and xeus stacks.
  doc_url: https://xtl.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtl

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
    - conda-forge/xtensor
