travis:
  secure:
    BINSTAR_TOKEN: A4fEyu0BRJGY2DGf9nqGjllQwsxOHCrHbH2e0KoAIjYcJpRa+5w4i2mtLHfABzQs3VAOO76XRKdUQmv8e+To5uYvOEFP3A5lMKgPzLhQ+z8tYFhyhz1+RKKrUmAGb+R2KeiwR3MwwRc9ZqrQWT6rE0URyfjCWZ502/mlxvaSUbCOcizyIGhMkUv9c/mJx/FYzMq5QcfxkltiP4NG9q0u9J23B+kA8weJjif8JOdaunAormZIL212f/wMVQYmSzp/kLa86cINnbHTl4u6TM3ClemwmFGtG6V5HDyyUz7XxuBJJ0wGFDrM6+pjmcHIJG60YaZJyibWvOMPqtaovCTHVSNihK5qrN7GkqCTXofsLlrUR44GnXNfJkeyuhleFt42QCt2BK1IML0MGMVWWRa7ZwGKHIC1knjB1QBHazJ041ohAXJIJamqoDHabXwhuC4DcOrjOsGqw/4tsrUSVYF+Tx9All/TY8L4W3UQRXIr386oZrnrf1HFHIGKk0OfWjipwbhcOFUbmaqTY9dGN6rvxgUMKcS7Hh5U/I5/PGeIXkFxLsy/DhApy27ppSknpP0c8RBvzWo8YopXyaaBZ/RiBp3zmxqxp6YZdHG5KHmBX14ef1EIfssDoMWk+5R9W6qZ3EechidJOKaKnTd6JoJL9XB2C6yMCIwbZJQUoj3gug8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
